### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by pastukhov** [VaclavSynacek/RF24SN_Arduino_Client#1]
Hi!  I am getting 

home/artem/sketchbook/libraries/RF24SN_Arduino_Client/RF24SN.cpp: In member function ‘RF24SNPacket RF24SN::sendPacket(RF24SNPacket)’:
/home/artem/sketchbook/libraries/RF24SN_Arduino_Client/RF24SN.cpp:129:30: error: call of overloaded ‘openWritingPipe(int)’ is ambiguous
     _radio->openWritingPipe(0);

When compiling any of examples.

**Comment by nidayand** [comment]
I fixed this (hopefully correct) with a modification to RF24SN.cpp, row 129.. to the following:
`    uint32_t pg1 = 0;
    _radio->openWritingPipe(pg1);`

Clearly declaring the type of the variable to uint32_t
