### ISSUE TITLE
Not receiving ack

### ISSUE THREAD

**Issue by amirmab** [VaclavSynacek/RF24SN_Arduino_Client#2]
I am receiving messages correctly in raspberry also in MQTT , but it look like for some reason not receiving the ack , this is the result when I enable debug in RF24.h :
I have a delay of 5 second between messages

0000...OK.failure
Publishing value 456 to MQTT topic RF24SN/in/1/123
0000...OK.failure
Publishing value 457 to MQTT topic RF24SN/in/1/123
0000...OK.failure
Publishing value 458 to MQTT topic RF24SN/in/1/123
0000...OK.failure
Publishing value 459 to MQTT topic RF24SN/in/1/123
0000...OK.failure
Publishing value 460 to MQTT topic RF24SN/in/1/123
0000...OK.failure

**Comment by VaclavSynacek** [comment]
I am not sure I understand your problem correctly.

In RF24SN the ack is implemented by the library itself. The RF24 native acks are turned off on purpose (see lines 33-35 in RF24SN.cpp).
For the RF24SN level acks, you just need to check if `RF24SN::publish` returns true or false. If true, then RF24SN level ack has been received by the arduino and all is good.

If I missed the point, please share the Arduino script. Preferably full, but at least the part where you test for the ack reception. And which RF24SN server implementation are you using (the nodejs or CPP)?

**Comment by amirmab** [comment]
Thanks , It was my bad node address, they were not match, I changed just one of 2 addresses in .js file ,
don't you think that should be a variable ?

**Comment by VaclavSynacek** [comment]
You mean the base address? That could be a command line parameter for all server implementations, that is true. On the other hand I don't see why would anyone need to change it unless running more than one full network (more than one base station). And BTW the default 0xF0F0F0F000 is chosen according to RF24 recommendation to not transmit too long series of 1 or too long series of 0.

Anyway, pull request for changing that to command line param would be welcomed.
